site_name: ACF-Gamma Legal Codex
site_url: https://acf-gamma.github.io/
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Electrolize
    code: Courier Prime 
  features:
    - navigation.footer
    - navigation.tracking
    - toc.follow
plugins:   
  - search
  - meta
  - tags
markdown_extensions:
  - attr_list
  - pymdownx.mark
  - admonition
  - pymdownx.details
  - toc:
      title: On this page 
      permalink: true 
      toc_depth: 6
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sPmWfcJa3n
copyright: Copyright &copy; - ACF-Gamma 2024-2025
extra_css:
  - assets/stylesheets/extra.css